name:           radiant-websocket-example
version:        1.0
summary:        Example python snap app
description:    Example python snap app
confinement:    strict
grade:          devel

apps:
  radiant-websocket-example:
    command:    radiant-websocket-example
    plugs:      [network-bind]

parts:
  radiant-websocket-example:
    plugin:     python
