name:           radiant-websocket-example
version:        1.0
summary:        Example python snap app
description:    Example python snap app
confinement:    devmode
grade:          stable

apps:
  radiant-websocket-example:
    command:    radiant-websocket-example

parts:
  radiant-websocket-example:
    plugin:     python
